server:
  port: 8080
spring:
  application:
    name: accounts



build:
  version: "1.0"

accounts:
  message: "my message"
  contactDetails:
    name: "Omar"
    email: "something@hotmail.com"
  onCallSupport:
    - (555) 555-1234
