server:
  port: 8082
spring:
  application:
    name: cards

#  profiles:
#    activate: "qa"


build:
  version: "1.0"

cards:
  message: "my message"
  contactDetails:
    name: "Omar"
    email: "something@hotmail.com"
  onCallSupport:
    - (555) 555-1234
