server:
  port: 8090
spring:
  application:
    name: loans

#  profiles:
#    activate: "qa"


build:
  version: "1.0"

loans:
  message: "my message"
  contactDetails:
    name: "Omar"
    email: "something@hotmail.com"
  onCallSupport:
    - (555) 555-1234
